using System;
using System.Collections.ObjectModel;

namespace Helper.Data.Vcard
{
    /// <summary>
    /// Container class for vCard properties of vCard 2.1.
    /// Considering current implementation of vCard support in MS Outlook, MS Outlook Express, Yahoo Mail and Eudora etc.,
    /// the following properties and attributes are not supported:
    /// * Photo
    /// * Address labels
    /// * Delivery address types
    /// * Mailer
    /// * Timezone
    /// * EMail types
    /// * Sound
    /// * Public key
    /// * Extensions
    /// * Geo
    ///
    /// So this vCard implementation is expected to be compatible with standard vCard fields of the vCard generated by these programs.
    /// </summary>
    public class VCard
    {
        private readonly char[] _lineBreak = {'\n', '\r'};

        #region Singlar Properties

        private string _formattedName;
        private string _surname;
        private string _givenName;
        private string _middleName;
        private string _prefix;
        private string _suffix;
        private string _title;
        private string _department;
        private string _org;
        private string _note;
        private string _role;

        public string FormattedName
        {
            get { return _formattedName; }
            set { _formattedName = value.TrimEnd(_lineBreak); }
        }

        public string Surname
        {
            get { return _surname; }
            set { _surname = value.TrimEnd(_lineBreak); }
        }

        public string GivenName
        {
            get { return _givenName; }
            set { _givenName = value.TrimEnd(_lineBreak); }
        }

        public string MiddleName
        {
            get { return _middleName; }
            set { _middleName = value.TrimEnd(_lineBreak); }
        }

        public string Prefix
        {
            get { return _prefix; }
            set { _prefix = value.TrimEnd(_lineBreak); }
        }

        public string Suffix
        {
            get { return _suffix; }
            set { _suffix = value.TrimEnd(_lineBreak); }
        }

        public string Title
        {
            get { return _title; }
            set { _title = value.TrimEnd(_lineBreak); }
        }

        public DateTime Birthday { get; set; }

        /// <summary>
        /// If Rev in vCard is UTC, Rev will convert utc to local datetime.
        /// </summary>
        public DateTime Rev { get; set; } = DateTime.MinValue;

        public string Organization
        {
            get { return _org; }
            set { _org = value.TrimEnd(_lineBreak); }
        }

        public string Department
        {
            get { return _department; }
            set { _department = value.TrimEnd(_lineBreak); }
        }

        public string Note
        {
            get { return _note; }
            set { _note = value.TrimEnd(_lineBreak); }
        }

        public string Role
        {
            get { return _role; }
            set { _role = value.TrimEnd(_lineBreak); }
        }

        #endregion

        #region Property Collections with attribute

        public Collection<Address> Addresses { get; set; } = new Collection<Address>();

        public Collection<PhoneNumber> Phones { get; set; } = new Collection<PhoneNumber>();

        public Collection<EmailAddress> Emails { get; set; } = new Collection<EmailAddress>();

        public Collection<Url> Urls { get; set; } = new Collection<Url>();

        #endregion

    }
}